name: siyuan
version: ${project.version}
main: com.ethercats.siyuan.SiYuanPlugin
api-version: '1.21'
description: 思渊 - 聚合通行证/任务/商店/传送插件
authors: [EtherCats]
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - LuckPerms

commands:
  gc:
    description: siyuan 聚合功能主命令
    usage: /gc <pass|quest|season|shop|wp|menu|reload|help>
    permission: siyuan.use

permissions:
  siyuan.use:
    description: 使用思渊基础功能
    default: true
  siyuan.admin:
    description: 思渊管理员权限
    default: op
  siyuan.pass.free:
    description: 免费档通行证
    default: true
  siyuan.pass.premium:
    description: 付费档通行证
    default: false
  siyuan.pass.vip:
    description: VIP 档通行证
    default: false
